---
title: "Summary"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Psychology Paper: It's All In Your Head: Expectations Create Illusory Perception In A Dual-Task Set Up
https://www-sciencedirect-com.ez-proxy.brooklyn.cuny.edu/science/article/pii/S1053810018302228

In this paper, the authors explain that the perception focuses on two things, sensory data and prior knowledge. One of these aspects many dominate the other if one of them is degraded in a way. The reliability of sensory data is dependent on attention. In this experiment, a dual task setting is used in which participants are often asked about the stimuli relevant for one task and only rarely are they asked about the stimuli relevant for another task. Through this, the experimenters wanted to understand why some participants perceive illusory stimuli while others don’t, the necessary ingredients of an experimental paradigm that is designed to elicit illusory perception, and what type of attention illusory perception is dependent on. They also used an autism spectrum quotient which measures autism-like traits in a subclinical population due to autism’s relationship with prediction errors. The researchers understand that autistic participants tend to exhibit reduced susceptibility to certain illusions and they expected that participants with higher AQ scores will experience less illusory perception. In order to perform the experiments, a computer-controlled experimental display a SUN CM751U CRT monitor with 1024×768 pixels resolution and 100 Hz refresh rate as well as the Radboud Faces Database was used. 
In the first experiment, there were ten female and six male participants, and they were tasked with identifying the gender of the image on the screen. There was also an arrow cue that would point to the left or the right of the screen for 150 ms. The image would also appear either on the left or the right side of the screen. Participants fixated on a cross in the center of the screen and then direct their attention to the cued location. On 90% of the trials, the participants were asked to identify the gender using the keyboard. On 10% of the trials, the auxiliary task was implemented in which participants were asked to rate the clarity of the square surrounding the image on the screen. On six trials, the participants were asked about the clarity of the box even though the square was not present. On the critical trials where the square was not presented, participants did not use a rating greater than 1 for visibility. Around 50% of the critical trails, some experience of the missing stimulus was reported. Their tests proved that cue was helpful in recognizing the faces. When the critical trails were removed, they found that spatial attention did not affect the visibility of the square. They also found that the participants failed to observe the square when it was present. Finally, there was no correlation between the AQ scores and the amount of non-critical trials where the participants experienced no stimulus.
There were two parts in the second experiment that used the same participants. In the first part of the experiment, the participants were presented with two faces on the left and right side of the screen. The faces were presented in four conditions: left and right face upright, left and right face inverted 180 degrees, left face inverted and right face upright, left face upright and right face inverted. All these conditions were presented an equal number of times. There was a Landolt square in between the faces. On 90% of the trials, participants had to determine whether the faces were positioned the same way. On 10% of the trials, the participants had to rate the visibility of the Landolt square. They observed that participants observed stimuli that were not on the screen. This illusory perception was correlated with the visibility rating in the non-critical trials and critical trials. There was no statistical significance between the AQ scores and the illusory perception score. 
 In the second part of the experiment, there were four circles in the corners and letters of the English alphabet in the middle, including all consonants and the letter y.  The circles were vertically color-bisected and they could be all the same arrangement or one circle could be the opposite arrangement. In the first block of the experiment, the participants were asked to ignore the letters and focus on the circles and determine if they were all the same or if there was an odd one out. In the second block of the experiment, the participants were asked to focus on the letters. In the dual task experiment, participants were instructed to pay attention to the whole screen and be prepared to perform either task. In this experiment, the participants experienced less illusionary perception than in the first part of experiment 2. There was a positive correlation between the illusory perception score and the visibility ratings in the non-critical trials. There was a difference between visibility ratings provided for trials when the letters were present compared to when they were absent. Some participants that they did not observe the letters when they were actually there. There was no statistical significance between the AQ scores and the illusory perception score.
	In this paper, the experimenters found that perception is a mixture of expectations and the incoming sensory data which can guide or misguide perception. They studied how expectations can create illusory perception when attention is diverted away from the stimuli. 
In all experiments, the experimenters found most participants observed stimuli that was not actually there. They were able to demonstrate that If there were more trials with the stimuli absent, the participants used the rating to state that they observed the object.  They did find variance within the individuals which could be associated with modulation of perception through expectations. There was no effect on spatial attention in illusory perception in this study. 


